config/routes.rb
Rails.application.routes.draw do

  root to: 'phrases#index'

  devise_for :users, :controllers => { registrations: 'user/registrations' }

  resources :phrases

  resources :users, only: [:show, :index]

  resources :phrases do
    member do
      post :vote
    end
    resources :examples, only: [:create, :destroy] do
      post :vote
    end
  end

  resources :notifications, only: :index do
    collection do
      put :read_all
    end
  end

end

app/views/layouts/_footer.slim
.navbar.row-fluid.text-center
  .navbar-inner
    .container
      footer.footer
        .small.my_footer#footerRight
          | Copyright © #{Time.now.year} &nbsp;
          = link_to 'Zalivan Vitaly', 'https://bitbucket.org/zalivanvit', target: '_blank'
          = link_to ' Dunice Alliance ', 'https://dunice.net/', target: '_blank'

app/views/layouts/_navigation.slim
header.navbar.navbar-inverse
  .container
    nav
      ul.nav.navbar-nav.pull-right
        li
        - if signed_in?
          li = link_to "Home", root_path
          li = link_to "Users", users_path
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              ' #{current_user.username}
              - if current_user.has_new_notifications?
                span.glyphicon.glyphicon-heart.navigation-notification-item
              span.caret
            ul.dropdown-menu
              li = link_to "View Profile", user_path(current_user)
              li = link_to "Edit Profile", edit_user_registration_path
              li = link_to notifications_path do
                - if current_user.has_new_notifications?
                  span.glyphicon.glyphicon-heart.navigation-notification-item
                ' Notifications
              li = link_to "Sign Out", destroy_user_session_path, method: "delete"
        - else
          li = link_to "Sign In", new_user_session_path
          li = link_to "Sign Up", new_user_registration_path

app/views/layouts/application.slim
doctype html
html
  head
    title Zalivan
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
    = action_cable_meta_tag

  body.container-fluid
    .row
      = render 'layouts/navigation'
      .col-md-6.col-md-offset-3
        - flash.each do |key, value|
          div class="alert alert-#{key}"
            = value

        = yield
        br
        = render 'layouts/footer'